server:
  port: 9996
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://124.223.14.20:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 5201314...
  redis:
    port: 6379
    password: 5201314...
    host: 124.223.14.20

mybatis:
  type-aliases-package: com.nsu.pojo
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    root: debug
