server:
  port: 9996
  ssl:
    enabled: false
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://124.223.14.20:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 5201314...
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    port: 6379
    password: 5201314...
    host: 124.223.14.20
    database: 0



mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    # 删除前
    logic-not-delete-value: 1
    # 删除后
    logic-delete-value: 0

logging:
  level:
    root: info
